#!/usr/bin/python

$ cat test.py 
#!/usr/bin/python

#OPEN A FILE

with open("/Users/javedalam/Documents/MyGit/Python/01-24-2019/new-file",mode='w') as f:
	f.write('My First Line\n')
	f.write('My Second Line\n\n')
	f.write('This is my third line\n')

O/P:

$ ./test.py 
Successful Completed

