#!/usr/bin/python

//BEST WAY TO OPEN A FILE IS 'with' STATEMENT
// BECAUSE IT ENSURES THAT FILE IS CLOSED WHEN THE BLOCK INSIDE 'with' IS EXITED
// WE DON'T NEED TO EXPLICITLY CALL THE 'close()' METHOD
// IT'S DONE INTERNALLY

with open("<path>/<file-name>",mode='rw+',encoding='utf-8') as f:

OR

with open("<path>/<file-name>",mode='rw+') as f:
