#!/usr/bin/python

# OPEN A FILE
# USE TRY..FINALLY FOR SAFER WAY
# THE CODE EXISTS WITHOUT CLOSING THE FILE

try:
	f = open("/Users/javedalam/Documents/MyGit/Python/12-07-2018/<file-name>.txt")
finally:
	f.close()
