#!/usr/bin/python

# OPEN A FILE IN READ MODE AND 'file-name.txt' should exist
f = open("/Users/javedalam/Documents/MyGit/Python/12-07-2018/<file-name>.txt")

# OPEN A FILE IN WRITE MODE
f = open("/Users/javedalam/Documents/MyGit/Python/12-07-2018/<file-name>.txt",mode = 'w')

# OPEN A FILE
# DEFAULT ENCODING IS PLATFORM INDEPENDENT
f = open("/Users/javedalam/Documents/MyGit/Python/12-07-2018/<file-name>.txt",mode='w',encoding='utf-8')

# OPEN A FILE FOR CERTAIN OPERATION AND CLOSE THE FILE
f = open("/Users/javedalam/Documents/MyGit/Python/12-07-2018/<file-name>.txt",mode='rw+')
f.close()



